name: CI/CD Pipeline

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run HTML Proofer to validate HTML files
      uses: chabad360/html-proofer-action@v1.0.0
      with:
        args: ./_site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
